# Use Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose dev port
EXPOSE 5173

# Run dev server
CMD ["npm", "run", "dev"]
